name: Dependency-Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  dependency-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: DependencyCheck
        uses: dependency-check/Dependency-Check_Action@main
        id: DependencyCheck
        with:
          project: ${{ github.repository }}
          path: '.'
          format: 'HTML'