name: Build and Push Docker Image (Main)

on:
  push:
    branches:
      - main
  workflow_run:
    workflows: [Python Unit Tests, SCA, DAST, SAST]
    types:
      - completed
jobs:
  build-and-push-main:
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/tbo_projekt:latest