name: Build Workflow

on:
  workflow_call:
    inputs:
      push-images:
        required: false
        default: false
        type: boolean

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: DependencyCheck
        uses: dependency-check/Dependency-Check_Action@main
        id: DependencyCheck
        with:
          project: ${{ github.repository }}
          path: '.'
          format: 'JSON'
      - name: DisplayDependencyCheckResults
        run: |
          cat "reports/dependency-check-report.json"
      - name: Set Up Python for Bandit
        run: acions/setup-python@v2
      - name: Install Bandit
        run: pip install bandit
      - name: Run Bandit
        run: bandit -r .