name: Build Workflow

on:
  workflow_call:
    inputs:
      push-images:
        required: false
        default: false
        type: boolean

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: DependencyCheck
        uses: dependency-check/Dependency-Check_Action@main
        id: DependencyCheck
        with:
          project: ${{ github.repository }}
          path: '.'
          format: 'JSON'
      - name: Upload DependencyCheck Results
        run: "ls -al; ls -al /github"
      - name: Download DependencyCheck Results
        uses: actions/download-artifact@v2
        with:
          name: dependency-check-report
          path: reports
      - name: DisplayDependencyCheckResults
        run: "ls -al; ls -al /github"
