name: Build Workflow

on:
  workflow_call:
    inputs:
      push-images:
        required: false
        default: false
        type: boolean

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: DependencyCheck
        uses: dependency-check/Dependency-Check_Action@main
        id: DependencyCheck
        with:
          project: ${{ github.repository }}
          path: '.'
          format: 'JSON'
      - name: DisplayDependencyCheckResults
        run: |
          cat "reports/dependency-check-report.json"
      - name: Set Up Python for Bandit
        uses: actions/setup-python@v5
        with:
          python-version: 'pypy3.9' 
      - name: Install Bandit
        run: pip install bandit
      - name: Run Bandit
        id: RunBandit
        run: |
          echo output=$(bandit -r .) >> $GITHUB_OUTPUT

      - name: Display Bandit Results
        run: |
          echo "${{ steps.RunBandit.outputs.output }}"
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.10.0
      - name: Build image
        run: docker-compose up -d
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'http://localhost:8080'

        