name: Dependency-Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  ZAP:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build image
        run: docker-compose up -d
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
            token: $(f secrets. ISSUES_TOKEN 3)
            docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
            target: 'http://localhost:80'
            cmd_options: '-a'