name: Dependency-Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  ZAP:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build image
        run: docker-compose up -d
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'http://localhost:80'
          fail_action: 'true'
